# This is a basic workflow to help you get started with Actions

name: Check code style


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  [ push, pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Generate antlr4 dependencies
        run: antlr4 -Dlanguage=Python3 -Xexact-output-dir project/lang.g4 -o project/lang

      - name: Run pytest
        run: |
          python ./scripts/run_tests.py
